# spring
spring:
  application:
    name: fish
  jackson:
    time-zone: GMT+8
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    lettuce:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 8
  cache:
    redis:
      time-to-live: 1d
      cache-null-values: false
  data:
    redis:
      repositories:
        enabled: false
  # profile active dev
  profiles:
    active: dev

# tomcat
server:
  address: 127.0.0.1
  port: 12001
  tomcat:
    basedir: ${user.home}/fish/tmp

# log
logging:
  file: ${user.home}/fish/fish.log
  level.com.nekolr: info
